# Generated by Django 5.1.3 on 2024-11-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='importedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.TextField()),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
